<<<<<<< HEAD
[jobs.c0]
image = {source = "dockerfile", path = ".", tag = "c0"}
run = [
  "java -jar build/libs/c0.jar -l $input -o $asm",
]
=======
[jobs.miniplc0]
image = {source = "dockerfile", path = ".", tag = "miniplc0-java"}
run = [
  "java -jar build/libs/miniplc0java.jar -l $input -o $output",
]
>>>>>>> 0dbb005... 修改
